name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 13.233.197.196
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          source: "."
          target: "/usr/share/nginx/html"

      - name: Restart nginx
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 13.233.197.196
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo systemctl restart nginx
